site_name: Magyar három szóban

theme:
  name: material
  custom_dir: overrides  # <- Added for theme overrides
  font:
    text: Inter  # Inter, Open Sans, Source Sans 3
    code: Fira Code  # (optional, if you want a nice monospace font)

extra_css:
  - css/morph.css
  - css/fonts.css

extra_javascript:
  - js/toggle-morph.js

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Journal:
      - Reggeli kutyaséta: week1.md
      - Ebéd a KaffeeHausban: week2.md

extra:
  footer: |
    Content licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences