site_name: Magyar három szóban

theme:
  name: material
  custom_dir: overrides  # <- Added for theme overrides
  font:
    text: Inter      # Open Sans, Inter,  Source Sans 3
    code: Fira Code  # (optional, if you want a nice monospace font)

extra_css:
  - css/morph.css
  - css/fonts.css

extra_javascript:
  - js/toggle-morph.js

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Journal:
      - "Reggeli kutyaséta":   week01.md
      - "A KaffeeHausban":     week02.md
      - "Egy séta a boltba":   week03.md
      - "Bentley éjjel ugat":  week04.md
      - "Miért tanultok?":     week05.md
      - "Kérsz kávét inni?":   week06.md
      - "Tessék vigyázni":     week07.md

extra:
  footer: |
    Content licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences