site_name: Magyar három szóban

theme:
  name: material
  custom_dir: overrides  # <- Added for theme overrides
  font:
    text: Inter      # Open Sans, Inter,  Source Sans 3
    code: Fira Code  # (optional, if you want a nice monospace font)

extra_css:
  - css/morph.css
  - css/fonts.css

extra_javascript:
  - js/toggle-morph.js

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Journal:
      - "Reggeli kutyaséta": week1B.md
      - "Ebéd a KaffeeHausban": week2.md
      - "Egy séta a boltba": week3.md
      - "Bentley éjjel ugat": week4.md

extra:
  footer: |
    Content licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences